services:
  - type: web
    name: hms-backend
    env: node
    plan: starter
    buildCommand: |
      # Install Chrome dependencies
      apt-get update && apt-get install -y \
        wget \
        gnupg \
        ca-certificates \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libdrm2 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libgbm1 \
        libxss1 \
        libu2f-udev \
        libvulkan1
      
      # Install Chrome
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable --no-install-recommends
      
      # Install dependencies and build
      npm install
      cd client && npm install --legacy-peer-deps && cd ..
      npm run build:server
      cd client && npm run build
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true